ALTER TABLE public.service_requests
  ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS first_contact_at TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS quoted_at TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS quote_file_url TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS quote_amount NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS quoted_by UUID REFERENCES public.profiles(id) DEFAULT NULL;